using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HiProtobuf.Lib
{
    class ProtoGenerate_java : ProtoGenerateBase
    {
        private string _folder = "/java";
        public ProtoGenerate_java(string name, List<VariableInfo> infos) : base(name, infos)
        {
            Path += _folder;
            if (Directory.Exists(Path))
            {
                Directory.Delete(Path, true);
            }
            Directory.CreateDirectory(Path);
            Path = Path + "/" + name + ".proto";

            var header = string.Format(@"
// This is auto generated by HiProtobuf
// Support: hiramtan@live.com

// [START declaration]
syntax = ""proto3"";
package HiProtobuf;

import ""google/protobuf/timestamp.proto"";
// [END declaration]

// [START java_declaration]
option java_package = ""com.example.HiProtobuf"";
option java_outer_classname = ""{0}"";
// [END java_declaration]

// [START csharp_declaration]
option csharp_namespace = ""HiProtobuf""; 
// [END csharp_declaration]
", name);
            header += "message " + name + " {";
            var sw = File.AppendText(Path);
            sw.WriteLine(header);
            sw.Close();
        }
    }
}
