/****************************************************************************
 * Description: 
 * 
 * Document: https://github.com/hiramtan/HiProtobuf
 * Author: hiramtan@live.com
 ****************************************************************************/

using System.Collections.Generic;
using System.IO;

namespace HiProtobuf.Lib
{
    class ProtoGenerate_java : ProtoGenerateBase
    {
        public ProtoGenerate_java(string name, List<VariableInfo> infos) : base(name, infos)
        {
            Path += Common.java_folder;
            if (Directory.Exists(Path))
            {
                Directory.Delete(Path, true);
            }
            Directory.CreateDirectory(Path);
            Path = Path + "/" + name + ".proto";

            var header = @"
// This is auto generated by HiProtobuf
// Support: hiramtan@live.com

// [START declaration]
syntax = ""proto3"";
package HiProtobuf;

import ""google/protobuf/timestamp.proto"";
// [END declaration]

// [START java_declaration]
option java_package = ""com.example.HiProtobuf"";
option java_outer_classname = ""java_outer_classname_wait_replace"";
// [END java_declaration]

// [START csharp_declaration]
option csharp_namespace = ""HiProtobuf""; 
// [END csharp_declaration]
";
            header = header.Replace("java_outer_classname_wait_replace", name);

            header += "message " + name + " {";
            var sw = File.AppendText(Path);
            sw.WriteLine(header);
            sw.Close();
        }
    }
}
