// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Example_Next.proto

package com.HiProtobuf.HiProtobuf;

public final class Example_Next_classname {
  private Example_Next_classname() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Example_NextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HiProtobuf.Example_Next)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 hp = 3;</code>
     */
    int getHp();

    /**
     * <code>int32 attack = 4;</code>
     */
    int getAttack();

    /**
     * <code>repeated string infos = 5;</code>
     */
    java.util.List<java.lang.String>
        getInfosList();
    /**
     * <code>repeated string infos = 5;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated string infos = 5;</code>
     */
    java.lang.String getInfos(int index);
    /**
     * <code>repeated string infos = 5;</code>
     */
    com.google.protobuf.ByteString
        getInfosBytes(int index);
  }
  /**
   * <pre>
   * [END csharp_declaration]
   * </pre>
   *
   * Protobuf type {@code HiProtobuf.Example_Next}
   */
  public  static final class Example_Next extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HiProtobuf.Example_Next)
      Example_NextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Example_Next.newBuilder() to construct.
    private Example_Next(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Example_Next() {
      name_ = "";
      infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Example_Next();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Example_Next(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              hp_ = input.readInt32();
              break;
            }
            case 32: {

              attack_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                infos_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              infos_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          infos_ = infos_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HiProtobuf.HiProtobuf.Example_Next_classname.internal_static_HiProtobuf_Example_Next_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HiProtobuf.HiProtobuf.Example_Next_classname.internal_static_HiProtobuf_Example_Next_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next.class, com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HP_FIELD_NUMBER = 3;
    private int hp_;
    /**
     * <code>int32 hp = 3;</code>
     */
    public int getHp() {
      return hp_;
    }

    public static final int ATTACK_FIELD_NUMBER = 4;
    private int attack_;
    /**
     * <code>int32 attack = 4;</code>
     */
    public int getAttack() {
      return attack_;
    }

    public static final int INFOS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList infos_;
    /**
     * <code>repeated string infos = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public java.lang.String getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInfosBytes(int index) {
      return infos_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (hp_ != 0) {
        output.writeInt32(3, hp_);
      }
      if (attack_ != 0) {
        output.writeInt32(4, attack_);
      }
      for (int i = 0; i < infos_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, infos_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (hp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, hp_);
      }
      if (attack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, attack_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < infos_.size(); i++) {
          dataSize += computeStringSizeNoTag(infos_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInfosList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next)) {
        return super.equals(obj);
      }
      com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next other = (com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getHp()
          != other.getHp()) return false;
      if (getAttack()
          != other.getAttack()) return false;
      if (!getInfosList()
          .equals(other.getInfosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + getHp();
      hash = (37 * hash) + ATTACK_FIELD_NUMBER;
      hash = (53 * hash) + getAttack();
      if (getInfosCount() > 0) {
        hash = (37 * hash) + INFOS_FIELD_NUMBER;
        hash = (53 * hash) + getInfosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [END csharp_declaration]
     * </pre>
     *
     * Protobuf type {@code HiProtobuf.Example_Next}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HiProtobuf.Example_Next)
        com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_NextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HiProtobuf.HiProtobuf.Example_Next_classname.internal_static_HiProtobuf_Example_Next_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HiProtobuf.HiProtobuf.Example_Next_classname.internal_static_HiProtobuf_Example_Next_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next.class, com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next.Builder.class);
      }

      // Construct using com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        hp_ = 0;

        attack_ = 0;

        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HiProtobuf.HiProtobuf.Example_Next_classname.internal_static_HiProtobuf_Example_Next_descriptor;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next getDefaultInstanceForType() {
        return com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next.getDefaultInstance();
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next build() {
        com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next buildPartial() {
        com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next result = new com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.hp_ = hp_;
        result.attack_ = attack_;
        if (((bitField0_ & 0x00000001) != 0)) {
          infos_ = infos_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infos_ = infos_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next) {
          return mergeFrom((com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next other) {
        if (other == com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getHp() != 0) {
          setHp(other.getHp());
        }
        if (other.getAttack() != 0) {
          setAttack(other.getAttack());
        }
        if (!other.infos_.isEmpty()) {
          if (infos_.isEmpty()) {
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfosIsMutable();
            infos_.addAll(other.infos_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int hp_ ;
      /**
       * <code>int32 hp = 3;</code>
       */
      public int getHp() {
        return hp_;
      }
      /**
       * <code>int32 hp = 3;</code>
       */
      public Builder setHp(int value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hp = 3;</code>
       */
      public Builder clearHp() {
        
        hp_ = 0;
        onChanged();
        return this;
      }

      private int attack_ ;
      /**
       * <code>int32 attack = 4;</code>
       */
      public int getAttack() {
        return attack_;
      }
      /**
       * <code>int32 attack = 4;</code>
       */
      public Builder setAttack(int value) {
        
        attack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 attack = 4;</code>
       */
      public Builder clearAttack() {
        
        attack_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          infos_ = new com.google.protobuf.LazyStringArrayList(infos_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInfosList() {
        return infos_.getUnmodifiableView();
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public int getInfosCount() {
        return infos_.size();
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public java.lang.String getInfos(int index) {
        return infos_.get(index);
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInfosBytes(int index) {
        return infos_.getByteString(index);
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder setInfos(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addInfos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<java.lang.String> values) {
        ensureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infos_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder clearInfos() {
        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addInfosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HiProtobuf.Example_Next)
    }

    // @@protoc_insertion_point(class_scope:HiProtobuf.Example_Next)
    private static final com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next();
    }

    public static com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Example_Next>
        PARSER = new com.google.protobuf.AbstractParser<Example_Next>() {
      @java.lang.Override
      public Example_Next parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Example_Next(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Example_Next> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Example_Next> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HiProtobuf.HiProtobuf.Example_Next_classname.Example_Next getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Example_Next_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Example_Next_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Example_Next.proto\022\nHiProtobuf\"S\n\014Exam" +
      "ple_Next\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\n\n\002hp" +
      "\030\003 \001(\005\022\016\n\006attack\030\004 \001(\005\022\r\n\005infos\030\005 \003(\tB@\n" +
      "\031com.HiProtobuf.HiProtobufB\026Example_Next" +
      "_classname\252\002\nHiProtobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HiProtobuf_Example_Next_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HiProtobuf_Example_Next_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Example_Next_descriptor,
        new java.lang.String[] { "Id", "Name", "Hp", "Attack", "Infos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
