// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Next.proto

package com.HiProtobuf.HiProtobuf;

public final class Next_classname {
  private Next_classname() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HiProtobuf.Next)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 hp = 3;</code>
     */
    int getHp();

    /**
     * <code>int32 attack = 4;</code>
     */
    int getAttack();

    /**
     * <code>repeated string infos = 5;</code>
     */
    java.util.List<java.lang.String>
        getInfosList();
    /**
     * <code>repeated string infos = 5;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated string infos = 5;</code>
     */
    java.lang.String getInfos(int index);
    /**
     * <code>repeated string infos = 5;</code>
     */
    com.google.protobuf.ByteString
        getInfosBytes(int index);
  }
  /**
   * <pre>
   * [END csharp_declaration]
   * </pre>
   *
   * Protobuf type {@code HiProtobuf.Next}
   */
  public  static final class Next extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HiProtobuf.Next)
      NextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Next.newBuilder() to construct.
    private Next(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Next() {
      name_ = "";
      infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Next();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Next(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              hp_ = input.readInt32();
              break;
            }
            case 32: {

              attack_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                infos_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              infos_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          infos_ = infos_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Next_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Next_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HiProtobuf.HiProtobuf.Next_classname.Next.class, com.HiProtobuf.HiProtobuf.Next_classname.Next.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HP_FIELD_NUMBER = 3;
    private int hp_;
    /**
     * <code>int32 hp = 3;</code>
     */
    public int getHp() {
      return hp_;
    }

    public static final int ATTACK_FIELD_NUMBER = 4;
    private int attack_;
    /**
     * <code>int32 attack = 4;</code>
     */
    public int getAttack() {
      return attack_;
    }

    public static final int INFOS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList infos_;
    /**
     * <code>repeated string infos = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public java.lang.String getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInfosBytes(int index) {
      return infos_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (hp_ != 0) {
        output.writeInt32(3, hp_);
      }
      if (attack_ != 0) {
        output.writeInt32(4, attack_);
      }
      for (int i = 0; i < infos_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, infos_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (hp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, hp_);
      }
      if (attack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, attack_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < infos_.size(); i++) {
          dataSize += computeStringSizeNoTag(infos_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInfosList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HiProtobuf.HiProtobuf.Next_classname.Next)) {
        return super.equals(obj);
      }
      com.HiProtobuf.HiProtobuf.Next_classname.Next other = (com.HiProtobuf.HiProtobuf.Next_classname.Next) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getHp()
          != other.getHp()) return false;
      if (getAttack()
          != other.getAttack()) return false;
      if (!getInfosList()
          .equals(other.getInfosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + getHp();
      hash = (37 * hash) + ATTACK_FIELD_NUMBER;
      hash = (53 * hash) + getAttack();
      if (getInfosCount() > 0) {
        hash = (37 * hash) + INFOS_FIELD_NUMBER;
        hash = (53 * hash) + getInfosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Next parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HiProtobuf.HiProtobuf.Next_classname.Next prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [END csharp_declaration]
     * </pre>
     *
     * Protobuf type {@code HiProtobuf.Next}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HiProtobuf.Next)
        com.HiProtobuf.HiProtobuf.Next_classname.NextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Next_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Next_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HiProtobuf.HiProtobuf.Next_classname.Next.class, com.HiProtobuf.HiProtobuf.Next_classname.Next.Builder.class);
      }

      // Construct using com.HiProtobuf.HiProtobuf.Next_classname.Next.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        hp_ = 0;

        attack_ = 0;

        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Next_descriptor;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Next_classname.Next getDefaultInstanceForType() {
        return com.HiProtobuf.HiProtobuf.Next_classname.Next.getDefaultInstance();
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Next_classname.Next build() {
        com.HiProtobuf.HiProtobuf.Next_classname.Next result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Next_classname.Next buildPartial() {
        com.HiProtobuf.HiProtobuf.Next_classname.Next result = new com.HiProtobuf.HiProtobuf.Next_classname.Next(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.hp_ = hp_;
        result.attack_ = attack_;
        if (((bitField0_ & 0x00000001) != 0)) {
          infos_ = infos_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infos_ = infos_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HiProtobuf.HiProtobuf.Next_classname.Next) {
          return mergeFrom((com.HiProtobuf.HiProtobuf.Next_classname.Next)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HiProtobuf.HiProtobuf.Next_classname.Next other) {
        if (other == com.HiProtobuf.HiProtobuf.Next_classname.Next.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getHp() != 0) {
          setHp(other.getHp());
        }
        if (other.getAttack() != 0) {
          setAttack(other.getAttack());
        }
        if (!other.infos_.isEmpty()) {
          if (infos_.isEmpty()) {
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfosIsMutable();
            infos_.addAll(other.infos_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HiProtobuf.HiProtobuf.Next_classname.Next parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HiProtobuf.HiProtobuf.Next_classname.Next) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int hp_ ;
      /**
       * <code>int32 hp = 3;</code>
       */
      public int getHp() {
        return hp_;
      }
      /**
       * <code>int32 hp = 3;</code>
       */
      public Builder setHp(int value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hp = 3;</code>
       */
      public Builder clearHp() {
        
        hp_ = 0;
        onChanged();
        return this;
      }

      private int attack_ ;
      /**
       * <code>int32 attack = 4;</code>
       */
      public int getAttack() {
        return attack_;
      }
      /**
       * <code>int32 attack = 4;</code>
       */
      public Builder setAttack(int value) {
        
        attack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 attack = 4;</code>
       */
      public Builder clearAttack() {
        
        attack_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          infos_ = new com.google.protobuf.LazyStringArrayList(infos_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInfosList() {
        return infos_.getUnmodifiableView();
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public int getInfosCount() {
        return infos_.size();
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public java.lang.String getInfos(int index) {
        return infos_.get(index);
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInfosBytes(int index) {
        return infos_.getByteString(index);
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder setInfos(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addInfos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<java.lang.String> values) {
        ensureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infos_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder clearInfos() {
        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addInfosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HiProtobuf.Next)
    }

    // @@protoc_insertion_point(class_scope:HiProtobuf.Next)
    private static final com.HiProtobuf.HiProtobuf.Next_classname.Next DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HiProtobuf.HiProtobuf.Next_classname.Next();
    }

    public static com.HiProtobuf.HiProtobuf.Next_classname.Next getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Next>
        PARSER = new com.google.protobuf.AbstractParser<Next>() {
      @java.lang.Override
      public Next parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Next(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Next> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Next> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HiProtobuf.HiProtobuf.Next_classname.Next getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Excel_NextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HiProtobuf.Excel_Next)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
     */
    int getNextsCount();
    /**
     * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
     */
    boolean containsNexts(
        int key);
    /**
     * Use {@link #getNextsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next>
    getNexts();
    /**
     * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
     */
    java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next>
    getNextsMap();
    /**
     * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
     */

    com.HiProtobuf.HiProtobuf.Next_classname.Next getNextsOrDefault(
        int key,
        com.HiProtobuf.HiProtobuf.Next_classname.Next defaultValue);
    /**
     * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
     */

    com.HiProtobuf.HiProtobuf.Next_classname.Next getNextsOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code HiProtobuf.Excel_Next}
   */
  public  static final class Excel_Next extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HiProtobuf.Excel_Next)
      Excel_NextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Excel_Next.newBuilder() to construct.
    private Excel_Next(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Excel_Next() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Excel_Next();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Excel_Next(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                nexts_ = com.google.protobuf.MapField.newMapField(
                    NextsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next>
              nexts__ = input.readMessage(
                  NextsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              nexts_.getMutableMap().put(
                  nexts__.getKey(), nexts__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Excel_Next_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetNexts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Excel_Next_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next.class, com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next.Builder.class);
    }

    public static final int NEXTS_FIELD_NUMBER = 1;
    private static final class NextsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next>newDefaultInstance(
                  com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Excel_Next_NextsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.HiProtobuf.HiProtobuf.Next_classname.Next.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> nexts_;
    private com.google.protobuf.MapField<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next>
    internalGetNexts() {
      if (nexts_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            NextsDefaultEntryHolder.defaultEntry);
      }
      return nexts_;
    }

    public int getNextsCount() {
      return internalGetNexts().getMap().size();
    }
    /**
     * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
     */

    public boolean containsNexts(
        int key) {
      
      return internalGetNexts().getMap().containsKey(key);
    }
    /**
     * Use {@link #getNextsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> getNexts() {
      return getNextsMap();
    }
    /**
     * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
     */

    public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> getNextsMap() {
      return internalGetNexts().getMap();
    }
    /**
     * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
     */

    public com.HiProtobuf.HiProtobuf.Next_classname.Next getNextsOrDefault(
        int key,
        com.HiProtobuf.HiProtobuf.Next_classname.Next defaultValue) {
      
      java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> map =
          internalGetNexts().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
     */

    public com.HiProtobuf.HiProtobuf.Next_classname.Next getNextsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> map =
          internalGetNexts().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetNexts(),
          NextsDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> entry
           : internalGetNexts().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next>
        nexts__ = NextsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, nexts__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next)) {
        return super.equals(obj);
      }
      com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next other = (com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next) obj;

      if (!internalGetNexts().equals(
          other.internalGetNexts())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetNexts().getMap().isEmpty()) {
        hash = (37 * hash) + NEXTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetNexts().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HiProtobuf.Excel_Next}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HiProtobuf.Excel_Next)
        com.HiProtobuf.HiProtobuf.Next_classname.Excel_NextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Excel_Next_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetNexts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableNexts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Excel_Next_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next.class, com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next.Builder.class);
      }

      // Construct using com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableNexts().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HiProtobuf.HiProtobuf.Next_classname.internal_static_HiProtobuf_Excel_Next_descriptor;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next getDefaultInstanceForType() {
        return com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next.getDefaultInstance();
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next build() {
        com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next buildPartial() {
        com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next result = new com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next(this);
        int from_bitField0_ = bitField0_;
        result.nexts_ = internalGetNexts();
        result.nexts_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next) {
          return mergeFrom((com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next other) {
        if (other == com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next.getDefaultInstance()) return this;
        internalGetMutableNexts().mergeFrom(
            other.internalGetNexts());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> nexts_;
      private com.google.protobuf.MapField<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next>
      internalGetNexts() {
        if (nexts_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              NextsDefaultEntryHolder.defaultEntry);
        }
        return nexts_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next>
      internalGetMutableNexts() {
        onChanged();;
        if (nexts_ == null) {
          nexts_ = com.google.protobuf.MapField.newMapField(
              NextsDefaultEntryHolder.defaultEntry);
        }
        if (!nexts_.isMutable()) {
          nexts_ = nexts_.copy();
        }
        return nexts_;
      }

      public int getNextsCount() {
        return internalGetNexts().getMap().size();
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
       */

      public boolean containsNexts(
          int key) {
        
        return internalGetNexts().getMap().containsKey(key);
      }
      /**
       * Use {@link #getNextsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> getNexts() {
        return getNextsMap();
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
       */

      public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> getNextsMap() {
        return internalGetNexts().getMap();
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
       */

      public com.HiProtobuf.HiProtobuf.Next_classname.Next getNextsOrDefault(
          int key,
          com.HiProtobuf.HiProtobuf.Next_classname.Next defaultValue) {
        
        java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> map =
            internalGetNexts().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
       */

      public com.HiProtobuf.HiProtobuf.Next_classname.Next getNextsOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> map =
            internalGetNexts().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearNexts() {
        internalGetMutableNexts().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
       */

      public Builder removeNexts(
          int key) {
        
        internalGetMutableNexts().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next>
      getMutableNexts() {
        return internalGetMutableNexts().getMutableMap();
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
       */
      public Builder putNexts(
          int key,
          com.HiProtobuf.HiProtobuf.Next_classname.Next value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableNexts().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Next&gt; Nexts = 1;</code>
       */

      public Builder putAllNexts(
          java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Next_classname.Next> values) {
        internalGetMutableNexts().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HiProtobuf.Excel_Next)
    }

    // @@protoc_insertion_point(class_scope:HiProtobuf.Excel_Next)
    private static final com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next();
    }

    public static com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Excel_Next>
        PARSER = new com.google.protobuf.AbstractParser<Excel_Next>() {
      @java.lang.Override
      public Excel_Next parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Excel_Next(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Excel_Next> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Excel_Next> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HiProtobuf.HiProtobuf.Next_classname.Excel_Next getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Next_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Next_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Excel_Next_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Excel_Next_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Excel_Next_NextsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Excel_Next_NextsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nNext.proto\022\nHiProtobuf\"K\n\004Next\022\n\n\002id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\022\n\n\002hp\030\003 \001(\005\022\016\n\006attack" +
      "\030\004 \001(\005\022\r\n\005infos\030\005 \003(\t\"~\n\nExcel_Next\0220\n\005N" +
      "exts\030\001 \003(\0132!.HiProtobuf.Excel_Next.Nexts" +
      "Entry\032>\n\nNextsEntry\022\013\n\003key\030\001 \001(\005\022\037\n\005valu" +
      "e\030\002 \001(\0132\020.HiProtobuf.Next:\0028\001B8\n\031com.HiP" +
      "rotobuf.HiProtobufB\016Next_classname\252\002\nHiP" +
      "rotobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HiProtobuf_Next_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HiProtobuf_Next_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Next_descriptor,
        new java.lang.String[] { "Id", "Name", "Hp", "Attack", "Infos", });
    internal_static_HiProtobuf_Excel_Next_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HiProtobuf_Excel_Next_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Excel_Next_descriptor,
        new java.lang.String[] { "Nexts", });
    internal_static_HiProtobuf_Excel_Next_NextsEntry_descriptor =
      internal_static_HiProtobuf_Excel_Next_descriptor.getNestedTypes().get(0);
    internal_static_HiProtobuf_Excel_Next_NextsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Excel_Next_NextsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
