// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.HiProtobuf.HiProtobuf;

public final class Test_classname {
  private Test_classname() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HiProtobuf.Test)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 hp = 3;</code>
     */
    int getHp();

    /**
     * <code>int32 attack = 4;</code>
     */
    int getAttack();

    /**
     * <code>repeated string infos = 5;</code>
     */
    java.util.List<java.lang.String>
        getInfosList();
    /**
     * <code>repeated string infos = 5;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated string infos = 5;</code>
     */
    java.lang.String getInfos(int index);
    /**
     * <code>repeated string infos = 5;</code>
     */
    com.google.protobuf.ByteString
        getInfosBytes(int index);
  }
  /**
   * Protobuf type {@code HiProtobuf.Test}
   */
  public  static final class Test extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HiProtobuf.Test)
      TestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Test.newBuilder() to construct.
    private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test() {
      id_ = "";
      name_ = "";
      infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Test();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              hp_ = input.readInt32();
              break;
            }
            case 32: {

              attack_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                infos_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              infos_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          infos_ = infos_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HiProtobuf.HiProtobuf.Test_classname.Test.class, com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HP_FIELD_NUMBER = 3;
    private int hp_;
    /**
     * <code>int32 hp = 3;</code>
     */
    public int getHp() {
      return hp_;
    }

    public static final int ATTACK_FIELD_NUMBER = 4;
    private int attack_;
    /**
     * <code>int32 attack = 4;</code>
     */
    public int getAttack() {
      return attack_;
    }

    public static final int INFOS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList infos_;
    /**
     * <code>repeated string infos = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public java.lang.String getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInfosBytes(int index) {
      return infos_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (hp_ != 0) {
        output.writeInt32(3, hp_);
      }
      if (attack_ != 0) {
        output.writeInt32(4, attack_);
      }
      for (int i = 0; i < infos_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, infos_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (hp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, hp_);
      }
      if (attack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, attack_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < infos_.size(); i++) {
          dataSize += computeStringSizeNoTag(infos_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInfosList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HiProtobuf.HiProtobuf.Test_classname.Test)) {
        return super.equals(obj);
      }
      com.HiProtobuf.HiProtobuf.Test_classname.Test other = (com.HiProtobuf.HiProtobuf.Test_classname.Test) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getHp()
          != other.getHp()) return false;
      if (getAttack()
          != other.getAttack()) return false;
      if (!getInfosList()
          .equals(other.getInfosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + getHp();
      hash = (37 * hash) + ATTACK_FIELD_NUMBER;
      hash = (53 * hash) + getAttack();
      if (getInfosCount() > 0) {
        hash = (37 * hash) + INFOS_FIELD_NUMBER;
        hash = (53 * hash) + getInfosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HiProtobuf.HiProtobuf.Test_classname.Test prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HiProtobuf.Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HiProtobuf.Test)
        com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HiProtobuf.HiProtobuf.Test_classname.Test.class, com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder.class);
      }

      // Construct using com.HiProtobuf.HiProtobuf.Test_classname.Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        hp_ = 0;

        attack_ = 0;

        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_descriptor;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Test getDefaultInstanceForType() {
        return com.HiProtobuf.HiProtobuf.Test_classname.Test.getDefaultInstance();
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Test build() {
        com.HiProtobuf.HiProtobuf.Test_classname.Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Test buildPartial() {
        com.HiProtobuf.HiProtobuf.Test_classname.Test result = new com.HiProtobuf.HiProtobuf.Test_classname.Test(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.hp_ = hp_;
        result.attack_ = attack_;
        if (((bitField0_ & 0x00000001) != 0)) {
          infos_ = infos_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infos_ = infos_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HiProtobuf.HiProtobuf.Test_classname.Test) {
          return mergeFrom((com.HiProtobuf.HiProtobuf.Test_classname.Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HiProtobuf.HiProtobuf.Test_classname.Test other) {
        if (other == com.HiProtobuf.HiProtobuf.Test_classname.Test.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getHp() != 0) {
          setHp(other.getHp());
        }
        if (other.getAttack() != 0) {
          setAttack(other.getAttack());
        }
        if (!other.infos_.isEmpty()) {
          if (infos_.isEmpty()) {
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfosIsMutable();
            infos_.addAll(other.infos_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HiProtobuf.HiProtobuf.Test_classname.Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HiProtobuf.HiProtobuf.Test_classname.Test) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int hp_ ;
      /**
       * <code>int32 hp = 3;</code>
       */
      public int getHp() {
        return hp_;
      }
      /**
       * <code>int32 hp = 3;</code>
       */
      public Builder setHp(int value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hp = 3;</code>
       */
      public Builder clearHp() {
        
        hp_ = 0;
        onChanged();
        return this;
      }

      private int attack_ ;
      /**
       * <code>int32 attack = 4;</code>
       */
      public int getAttack() {
        return attack_;
      }
      /**
       * <code>int32 attack = 4;</code>
       */
      public Builder setAttack(int value) {
        
        attack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 attack = 4;</code>
       */
      public Builder clearAttack() {
        
        attack_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          infos_ = new com.google.protobuf.LazyStringArrayList(infos_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInfosList() {
        return infos_.getUnmodifiableView();
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public int getInfosCount() {
        return infos_.size();
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public java.lang.String getInfos(int index) {
        return infos_.get(index);
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInfosBytes(int index) {
        return infos_.getByteString(index);
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder setInfos(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addInfos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<java.lang.String> values) {
        ensureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infos_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder clearInfos() {
        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addInfosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HiProtobuf.Test)
    }

    // @@protoc_insertion_point(class_scope:HiProtobuf.Test)
    private static final com.HiProtobuf.HiProtobuf.Test_classname.Test DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HiProtobuf.HiProtobuf.Test_classname.Test();
    }

    public static com.HiProtobuf.HiProtobuf.Test_classname.Test getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test>
        PARSER = new com.google.protobuf.AbstractParser<Test>() {
      @java.lang.Override
      public Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HiProtobuf.HiProtobuf.Test_classname.Test getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Excel_TestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HiProtobuf.Excel_Test)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    java.util.List<com.HiProtobuf.HiProtobuf.Test_classname.Test> 
        getDataList();
    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    com.HiProtobuf.HiProtobuf.Test_classname.Test getData(int index);
    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    java.util.List<? extends com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HiProtobuf.Excel_Test}
   */
  public  static final class Excel_Test extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HiProtobuf.Excel_Test)
      Excel_TestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Excel_Test.newBuilder() to construct.
    private Excel_Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Excel_Test() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Excel_Test();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Excel_Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = new java.util.ArrayList<com.HiProtobuf.HiProtobuf.Test_classname.Test>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                  input.readMessage(com.HiProtobuf.HiProtobuf.Test_classname.Test.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.class, com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.HiProtobuf.HiProtobuf.Test_classname.Test> data_;
    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    public java.util.List<com.HiProtobuf.HiProtobuf.Test_classname.Test> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    public java.util.List<? extends com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    public com.HiProtobuf.HiProtobuf.Test_classname.Test getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .HiProtobuf.Test Data = 1;</code>
     */
    public com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test)) {
        return super.equals(obj);
      }
      com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test other = (com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test) obj;

      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HiProtobuf.Excel_Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HiProtobuf.Excel_Test)
        com.HiProtobuf.HiProtobuf.Test_classname.Excel_TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.class, com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.Builder.class);
      }

      // Construct using com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_descriptor;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test getDefaultInstanceForType() {
        return com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.getDefaultInstance();
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test build() {
        com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test buildPartial() {
        com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test result = new com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test) {
          return mergeFrom((com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test other) {
        if (other == com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.HiProtobuf.HiProtobuf.Test_classname.Test> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = new java.util.ArrayList<com.HiProtobuf.HiProtobuf.Test_classname.Test>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.HiProtobuf.HiProtobuf.Test_classname.Test, com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder, com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder> dataBuilder_;

      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public java.util.List<com.HiProtobuf.HiProtobuf.Test_classname.Test> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.Test_classname.Test getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public Builder setData(
          int index, com.HiProtobuf.HiProtobuf.Test_classname.Test value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public Builder setData(
          int index, com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public Builder addData(com.HiProtobuf.HiProtobuf.Test_classname.Test value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public Builder addData(
          int index, com.HiProtobuf.HiProtobuf.Test_classname.Test value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public Builder addData(
          com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public Builder addData(
          int index, com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.HiProtobuf.HiProtobuf.Test_classname.Test> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public java.util.List<? extends com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.HiProtobuf.HiProtobuf.Test_classname.Test.getDefaultInstance());
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.HiProtobuf.HiProtobuf.Test_classname.Test.getDefaultInstance());
      }
      /**
       * <code>repeated .HiProtobuf.Test Data = 1;</code>
       */
      public java.util.List<com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.HiProtobuf.HiProtobuf.Test_classname.Test, com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder, com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.HiProtobuf.HiProtobuf.Test_classname.Test, com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder, com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HiProtobuf.Excel_Test)
    }

    // @@protoc_insertion_point(class_scope:HiProtobuf.Excel_Test)
    private static final com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test();
    }

    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Excel_Test>
        PARSER = new com.google.protobuf.AbstractParser<Excel_Test>() {
      @java.lang.Override
      public Excel_Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Excel_Test(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Excel_Test> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Excel_Test> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Test_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Test_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Excel_Test_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Excel_Test_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTest.proto\022\nHiProtobuf\"K\n\004Test\022\n\n\002id\030\001" +
      " \001(\t\022\014\n\004name\030\002 \001(\t\022\n\n\002hp\030\003 \001(\005\022\016\n\006attack" +
      "\030\004 \001(\005\022\r\n\005infos\030\005 \003(\t\",\n\nExcel_Test\022\036\n\004D" +
      "ata\030\001 \003(\0132\020.HiProtobuf.TestB7\n\031com.HiPro" +
      "tobuf.HiProtobufB\016Test_classname\252\002\tTable" +
      "Toolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HiProtobuf_Test_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HiProtobuf_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Test_descriptor,
        new java.lang.String[] { "Id", "Name", "Hp", "Attack", "Infos", });
    internal_static_HiProtobuf_Excel_Test_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HiProtobuf_Excel_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Excel_Test_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
