// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Example.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace TableTool {

  #region Messages
  public sealed class Example : pb::IMessage {
    private static readonly pb::MessageParser<Example> _parser = new pb::MessageParser<Example>(() => new Example());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Example> Parser { get { return _parser; } }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name1" field.</summary>
    public const int Name1FieldNumber = 2;
    private double name1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Name1 {
      get { return name1_; }
      set {
        name1_ = value;
      }
    }

    /// <summary>Field number for the "name2" field.</summary>
    public const int Name2FieldNumber = 3;
    private float name2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Name2 {
      get { return name2_; }
      set {
        name2_ = value;
      }
    }

    /// <summary>Field number for the "name3" field.</summary>
    public const int Name3FieldNumber = 4;
    private int name3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Name3 {
      get { return name3_; }
      set {
        name3_ = value;
      }
    }

    /// <summary>Field number for the "name4" field.</summary>
    public const int Name4FieldNumber = 5;
    private long name4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Name4 {
      get { return name4_; }
      set {
        name4_ = value;
      }
    }

    /// <summary>Field number for the "name5" field.</summary>
    public const int Name5FieldNumber = 6;
    private uint name5_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Name5 {
      get { return name5_; }
      set {
        name5_ = value;
      }
    }

    /// <summary>Field number for the "name6" field.</summary>
    public const int Name6FieldNumber = 7;
    private ulong name6_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Name6 {
      get { return name6_; }
      set {
        name6_ = value;
      }
    }

    /// <summary>Field number for the "name7" field.</summary>
    public const int Name7FieldNumber = 8;
    private bool name7_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Name7 {
      get { return name7_; }
      set {
        name7_ = value;
      }
    }

    /// <summary>Field number for the "name8" field.</summary>
    public const int Name8FieldNumber = 9;
    private string name8_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name8 {
      get { return name8_; }
      set {
        name8_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name9" field.</summary>
    public const int Name9FieldNumber = 10;
    private static readonly pb::FieldCodec<double> _repeated_name9_codec
        = pb::FieldCodec.ForDouble(82);
    private readonly pbc::RepeatedField<double> name9_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<double> Name9 {
      get { return name9_; }
    }

    /// <summary>Field number for the "name10" field.</summary>
    public const int Name10FieldNumber = 11;
    private static readonly pb::FieldCodec<float> _repeated_name10_codec
        = pb::FieldCodec.ForFloat(90);
    private readonly pbc::RepeatedField<float> name10_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> Name10 {
      get { return name10_; }
    }

    /// <summary>Field number for the "name11" field.</summary>
    public const int Name11FieldNumber = 12;
    private static readonly pb::FieldCodec<int> _repeated_name11_codec
        = pb::FieldCodec.ForInt32(98);
    private readonly pbc::RepeatedField<int> name11_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Name11 {
      get { return name11_; }
    }

    /// <summary>Field number for the "name12" field.</summary>
    public const int Name12FieldNumber = 13;
    private static readonly pb::FieldCodec<long> _repeated_name12_codec
        = pb::FieldCodec.ForInt64(106);
    private readonly pbc::RepeatedField<long> name12_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> Name12 {
      get { return name12_; }
    }

    /// <summary>Field number for the "name13" field.</summary>
    public const int Name13FieldNumber = 14;
    private static readonly pb::FieldCodec<uint> _repeated_name13_codec
        = pb::FieldCodec.ForUInt32(114);
    private readonly pbc::RepeatedField<uint> name13_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> Name13 {
      get { return name13_; }
    }

    /// <summary>Field number for the "name14" field.</summary>
    public const int Name14FieldNumber = 15;
    private static readonly pb::FieldCodec<ulong> _repeated_name14_codec
        = pb::FieldCodec.ForUInt64(122);
    private readonly pbc::RepeatedField<ulong> name14_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> Name14 {
      get { return name14_; }
    }

    /// <summary>Field number for the "name15" field.</summary>
    public const int Name15FieldNumber = 16;
    private static readonly pb::FieldCodec<bool> _repeated_name15_codec
        = pb::FieldCodec.ForBool(130);
    private readonly pbc::RepeatedField<bool> name15_ = new pbc::RepeatedField<bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<bool> Name15 {
      get { return name15_; }
    }

    /// <summary>Field number for the "name16" field.</summary>
    public const int Name16FieldNumber = 17;
    private static readonly pb::FieldCodec<string> _repeated_name16_codec
        = pb::FieldCodec.ForString(138);
    private readonly pbc::RepeatedField<string> name16_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Name16 {
      get { return name16_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name1 != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Name1);
      }
      if (Name2 != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Name2);
      }
      if (Name3 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Name3);
      }
      if (Name4 != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Name4);
      }
      if (Name5 != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Name5);
      }
      if (Name6 != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(Name6);
      }
      if (Name7 != false) {
        output.WriteRawTag(64);
        output.WriteBool(Name7);
      }
      if (Name8.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Name8);
      }
      name9_.WriteTo(output, _repeated_name9_codec);
      name10_.WriteTo(output, _repeated_name10_codec);
      name11_.WriteTo(output, _repeated_name11_codec);
      name12_.WriteTo(output, _repeated_name12_codec);
      name13_.WriteTo(output, _repeated_name13_codec);
      name14_.WriteTo(output, _repeated_name14_codec);
      name15_.WriteTo(output, _repeated_name15_codec);
      name16_.WriteTo(output, _repeated_name16_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name1 != 0D) {
        size += 1 + 8;
      }
      if (Name2 != 0F) {
        size += 1 + 4;
      }
      if (Name3 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Name3);
      }
      if (Name4 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Name4);
      }
      if (Name5 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Name5);
      }
      if (Name6 != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Name6);
      }
      if (Name7 != false) {
        size += 1 + 1;
      }
      if (Name8.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name8);
      }
      size += name9_.CalculateSize(_repeated_name9_codec);
      size += name10_.CalculateSize(_repeated_name10_codec);
      size += name11_.CalculateSize(_repeated_name11_codec);
      size += name12_.CalculateSize(_repeated_name12_codec);
      size += name13_.CalculateSize(_repeated_name13_codec);
      size += name14_.CalculateSize(_repeated_name14_codec);
      size += name15_.CalculateSize(_repeated_name15_codec);
      size += name16_.CalculateSize(_repeated_name16_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 17: {
            Name1 = input.ReadDouble();
            break;
          }
          case 29: {
            Name2 = input.ReadFloat();
            break;
          }
          case 32: {
            Name3 = input.ReadInt32();
            break;
          }
          case 40: {
            Name4 = input.ReadInt64();
            break;
          }
          case 48: {
            Name5 = input.ReadUInt32();
            break;
          }
          case 56: {
            Name6 = input.ReadUInt64();
            break;
          }
          case 64: {
            Name7 = input.ReadBool();
            break;
          }
          case 74: {
            Name8 = input.ReadString();
            break;
          }
          case 82:
          case 81: {
            name9_.AddEntriesFrom(input, _repeated_name9_codec);
            break;
          }
          case 90:
          case 93: {
            name10_.AddEntriesFrom(input, _repeated_name10_codec);
            break;
          }
          case 98:
          case 96: {
            name11_.AddEntriesFrom(input, _repeated_name11_codec);
            break;
          }
          case 106:
          case 104: {
            name12_.AddEntriesFrom(input, _repeated_name12_codec);
            break;
          }
          case 114:
          case 112: {
            name13_.AddEntriesFrom(input, _repeated_name13_codec);
            break;
          }
          case 122:
          case 120: {
            name14_.AddEntriesFrom(input, _repeated_name14_codec);
            break;
          }
          case 130:
          case 128: {
            name15_.AddEntriesFrom(input, _repeated_name15_codec);
            break;
          }
          case 138: {
            name16_.AddEntriesFrom(input, _repeated_name16_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class Excel_Example : pb::IMessage {
    private static readonly pb::MessageParser<Excel_Example> _parser = new pb::MessageParser<Excel_Example>(() => new Excel_Example());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Excel_Example> Parser { get { return _parser; } }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 1;
    private static readonly pb::FieldCodec<global::TableTool.Example> _repeated_data_codec
        = pb::FieldCodec.ForMessage(10, global::TableTool.Example.Parser);
    private readonly pbc::RepeatedField<global::TableTool.Example> data_ = new pbc::RepeatedField<global::TableTool.Example>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::TableTool.Example> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      data_.WriteTo(output, _repeated_data_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += data_.CalculateSize(_repeated_data_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
