# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Example_Test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Example_Test.proto',
  package='HiProtobuf',
  syntax='proto3',
  serialized_options=_b('\n\031com.HiProtobuf.HiProtobufB\026Example_Test_classname\252\002\nHiProtobuf'),
  serialized_pb=_b('\n\x12\x45xample_Test.proto\x12\nHiProtobuf\"S\n\x0c\x45xample_Test\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02hp\x18\x03 \x01(\x05\x12\x0e\n\x06\x61ttack\x18\x04 \x01(\x05\x12\r\n\x05infos\x18\x05 \x03(\tB@\n\x19\x63om.HiProtobuf.HiProtobufB\x16\x45xample_Test_classname\xaa\x02\nHiProtobufb\x06proto3')
)




_EXAMPLE_TEST = _descriptor.Descriptor(
  name='Example_Test',
  full_name='HiProtobuf.Example_Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='HiProtobuf.Example_Test.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='HiProtobuf.Example_Test.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hp', full_name='HiProtobuf.Example_Test.hp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attack', full_name='HiProtobuf.Example_Test.attack', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infos', full_name='HiProtobuf.Example_Test.infos', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Example_Test'] = _EXAMPLE_TEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Example_Test = _reflection.GeneratedProtocolMessageType('Example_Test', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLE_TEST,
  '__module__' : 'Example_Test_pb2'
  # @@protoc_insertion_point(class_scope:HiProtobuf.Example_Test)
  })
_sym_db.RegisterMessage(Example_Test)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
